/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SerialRouteImport } from './routes/serial'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ThresholdsRouteImport } from './routes/thresholds'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SerialRoute = SerialRouteImport.update({
  id: '/serial',
  path: '/serial',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ThresholdsRoute = ThresholdsRouteImport.update({
  id: '/thresholds',
  path: '/thresholds',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/engine': typeof EngineRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/reports': typeof ReportsRoute
  '/serial': typeof SerialRoute
  '/settings': typeof SettingsRoute
  '/thresholds': typeof ThresholdsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/engine': typeof EngineRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/reports': typeof ReportsRoute
  '/serial': typeof SerialRoute
  '/settings': typeof SettingsRoute
  '/thresholds': typeof ThresholdsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/engine': typeof EngineRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/patients': typeof PatientsRoute
  '/reports': typeof ReportsRoute
  '/serial': typeof SerialRoute
  '/settings': typeof SettingsRoute
  '/thresholds': typeof ThresholdsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/engine'
    | '/history'
    | '/live'
    | '/login'
    | '/patients'
    | '/reports'
    | '/serial'
    | '/settings'
    | '/thresholds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/engine'
    | '/history'
    | '/live'
    | '/login'
    | '/patients'
    | '/reports'
    | '/serial'
    | '/settings'
    | '/thresholds'
  id:
    | '__root__'
    | '/'
    | '/engine'
    | '/history'
    | '/live'
    | '/login'
    | '/patients'
    | '/reports'
    | '/serial'
    | '/settings'
    | '/thresholds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EngineRoute: typeof EngineRoute
  HistoryRoute: typeof HistoryRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  PatientsRoute: typeof PatientsRoute
  ReportsRoute: typeof ReportsRoute
  SerialRoute: typeof SerialRoute
  SettingsRoute: typeof SettingsRoute
  ThresholdsRoute: typeof ThresholdsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serial': {
      id: '/serial'
      path: '/serial'
      fullPath: '/serial'
      preLoaderRoute: typeof SerialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thresholds': {
      id: '/thresholds'
      path: '/thresholds'
      fullPath: '/thresholds'
      preLoaderRoute: typeof ThresholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EngineRoute: EngineRoute,
  HistoryRoute: HistoryRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  PatientsRoute: PatientsRoute,
  ReportsRoute: ReportsRoute,
  SerialRoute: SerialRoute,
  SettingsRoute: SettingsRoute,
  ThresholdsRoute: ThresholdsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
